version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/app
    working_dir: /app/public
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: php -S 0.0.0.0:8000

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
